CLaserOdometry2DNode:
  ros__parameters:
    laser_scan_topic: /scan_fixed
    odom_topic: /odom_rf2o
    publish_tf: true
    base_frame_id: base_link
    odom_frame_id: odom
    init_pose_from_topic: ''
    freq: 20.0