<?xml version="1.0"?>
<package format="3">
  <name>lidar_avoidance</name>
  <version>0.0.1</version>
  <description>Simple LaserScan obstacle avoidance test node for ROS 2 Jazzy.</description>
  <maintainer email="team@example.com">lidar patrol team</maintainer>
  <license>Apache-2.0</license>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
