<?xml version="1.0"?>
<package format="3">
  <name>navigation</name>
  <version>0.0.1</version>
  <description>巡检车自主导航与定制路线</description>
  <maintainer email="23121826@example.com">龚欣卉</maintainer>
  <license>Apache-2.0</license>
  <depend>rclpy</depend>
  <depend>nav_msgs</depend>
  <depend>nav2_msgs</depend>
  <depend>action_msgs</depend>
  <depend>tf2_ros</depend>
  <export><build_type>ament_python</build_type></export>
</package>
